# docker run -d -it -v /path/on/host:/data -e EULA=TRUE -p 25565:25565 --name mc itzg/minecraft-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scramblecraft01-server
  namespace: minecraft
  labels:
    app: scramblecraft01-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scramblecraft01-server
  template:
    metadata:
      labels:
        app: scramblecraft01-server
    spec:
      volumes:
      - name: scramblecraft01-data
        persistentVolumeClaim:
          claimName: scramblecraft01-data-pvc
      containers:
      - name: scramblecraft01-server
        image: itzg/minecraft-server:java8
        resources:
          limits:
            memory: 8Gi
          requests:
            memory: 4Gi
        env:
          - name:  EULA
            value: 'TRUE'
          - name: MODE
            value: survival
          - name: MOTD
            value: Welcome to the server!
          - name: TYPE
            value: FORGE
          - name: VERSION
            value: 1.12.2
          - name: FORGE_VERSION
            value: 14.23.5.2854
          - name: PVP
            value: 'FALSE'
          - name: MEMORY
            value: 6G
        ports:
        - containerPort: 25565
          name: scramblecraft01
        volumeMounts:
          - name: scramblecraft01-data
            mountPath:  /data
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 1.1.1.1
