---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: scramblecraft01-data
  namespace: scramblecraft01
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    # Edit this to be an actual path on your server's filesystem
    path: /mnt/local-volumes/scramblecraft01
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-worker-02  # Edit this to be an actual kubernetes name of your server
