apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scramblecraft01-data-pvc
  namespace: minecraft
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
